language: erlang
script: make test
branches:
  only:
    - master
notifications:
  email: phillip@flitbit.com
env:
  - R16B03-01
  - R16B03
  - R16B02
  - R16B01
  - R16B
  - R16A
  - R15B01
  - R15B
  - R14B04
  - R14B03
  - R14B02
